### ISSUE TITLE
Goes against TypeScript Design Goals?

### ISSUE THREAD

**Issue by tannerntannern** [kimamula/ts-transformer-keys#37]
Interesting project!  However, according to the [TypeScript design goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals), it seems that having the type system "leak" into runtime would go against the goal of a "fully erasable type system."

_I don't intend to just be a naysayer!_  I want to know more about the thinking behind this project and what it solves that can't be solved in TypeScript as it stands today.

**Comment by kimamula** [comment]
In my opinion, it is because TypeScript itself does not aim to make type information available on run-time that the functionality of enabling developers to customize the transformation to achieve that at their own risk is valuable.

I think there are better places to discuss this issue, like [here](https://github.com/microsoft/TypeScript/issues/14419).
